name: build
on:
  push:
    branches:
      - v1.x
      - v2.x
      - v3.x
jobs:
  build-toolchain:
    name: Publish toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish toolchain
        run: |
          ./scripts/build -p -i toolchain .
  build-base:
    name: Publish base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish base image
        run: |
          ./scripts/build -p -i base .
  get-other-image-names:
    name: Get other image names
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the Git repository
          uses: actions/checkout@v3
        - id: images-matrix
          run: |
            jq '.images | to_entries | map(select(.value."stage3-image"))[].key' images.json >> $GITHUB_OUTPUT
  build-other:
    name: Publish other images
    runs-on: ubuntu-latest
    needs: [build-toolchain, build-base, get-other-image-names]
    strategy:
      matrix: ${{ fromJson(needs.get-other-image-names.outputs.images-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish ${{ matrix.image }}
        run: |
          ./scripts/build -p -i ${{ matrix.image }} .
