name: build
on:
  push:
    branches:
      - v1.x
      - v2.x
      - v3.x
jobs:
  build:
    name: Publish latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Build and publish images
        run: |
          ./scripts/build -p .
  armbuild:
    name: Build latest arm64
    runs-on: macos-14
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v2
      - name: Setup Docker
        run: |
          brew install docker colima docker-buildx
      - name: Hotfix QEMU
        run: |
          cat >entitlements.xml <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>com.apple.security.hypervisor</key>
              <true/>
          </dict>
          </plist>
          EOF
          codesign --sign - --entitlements entitlements.xml --force /opt/homebrew/bin/qemu-system-aarch64
      - name: Start Docker container runtimes
        run: |
          colima start
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish images
        run: |
          ./scripts/build -a .
