name: release
on:
  push:
    tags:
      - '*'
jobs:
  release-toolchain:
    name: Publish a release toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish images
        run: |
          version="$(echo "${{ github.ref }}" | cut -d / -f 3)"
          ./scripts/build -p -i toolchain . "$version"
  release-base:
    name: Publish a release base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish images
        run: |
          version="$(echo "${{ github.ref }}" | cut -d / -f 3)"
          ./scripts/build -p -i base . "$version"
  get-other-image-names:
    name: Get other image names
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the Git repository
          uses: actions/checkout@v3
        - id: images-matrix
          run: |
            jq '.images | to_entries | map(select(.value."stage3-image"))[].key' images.json >> $GITHUB_OUTPUT
  release-other:
    name: Publish a release for other images
    runs-on: ubuntu-latest
    needs: [release-toolchain, release-base, get-other-image-names]
    strategy:
      matrix: ${{ fromJson(needs.get-other-image-names.outputs.images-matrix) }}
      fail-fast: false
    steps:
      - name: Checkout the Git repository
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: matteodelabre
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and publish images
        run: |
          version="$(echo "${{ github.ref }}" | cut -d / -f 3)"
          ./scripts/build -p -i ${{ matrix.image }} . "$version"
